# Generated by Django 4.1.7 on 2023-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jangoapp', '0002_students_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=25, null=True),
        ),
    ]
